# Generated by Django 4.1.1 on 2023-08-12 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=50)),
                ('contrasenea', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.CharField(blank=True, max_length=10, null=True)),
                ('terminal', models.CharField(blank=True, max_length=60, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=60, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=60, null=True)),
                ('rut_cliente', models.CharField(blank=True, max_length=60, null=True)),
                ('cliente', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_vendedor', models.CharField(blank=True, max_length=60, null=True)),
                ('observacion', models.CharField(blank=True, max_length=520, null=True)),
                ('monto_neto', models.PositiveIntegerField(blank=True, null=True)),
                ('iva', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo_klap', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_operacion', models.CharField(blank=True, max_length=60, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=60, null=True)),
                ('cliente', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_vendedor', models.CharField(blank=True, max_length=60, null=True)),
                ('observacion', models.CharField(blank=True, max_length=520, null=True)),
                ('subtotal', models.PositiveIntegerField(blank=True, null=True)),
                ('iva', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=60, null=True)),
                ('banco', models.CharField(blank=True, max_length=60, null=True)),
                ('iban', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contrasenea', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('superficie', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_inicial', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_termino', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=550, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_disponible', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lugar_de_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('boletas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.boleta')),
                ('facturas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.factura')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.PositiveIntegerField(null=True)),
                ('cobro_maestro', models.PositiveIntegerField(blank=True, null=True)),
                ('saldo_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('saldo_a_deber', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='nombre_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsociarMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.materiales')),
                ('nombre_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
