# Generated by Django 4.1.1 on 2023-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='proyectos_asociados',
            field=models.ManyToManyField(to='cabin_APP.proyecto'),
        ),
    ]
