# Generated by Django 4.1.1 on 2023-08-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0005_alter_materiales_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proyectos_asociados',
            field=models.ManyToManyField(blank=True, related_name='facturas_asociadas', to='cabin_APP.proyecto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_relacionadas', to='cabin_APP.proyecto'),
        ),
    ]
