# Generated by Django 4.1.1 on 2023-08-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0006_factura_proyectos_asociados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='proyectos_asociados',
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto'),
        ),
    ]
