# Generated by Django 4.1.1 on 2023-08-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0008_asociarfactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociarMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobro_maestro', models.PositiveIntegerField(blank=True, null=True)),
                ('Observacion', models.CharField(blank=True, max_length=600, null=True)),
                ('trabajo', models.CharField(blank=True, max_length=600, null=True)),
                ('nombre_maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.maestro')),
                ('nombre_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
