# Generated by Django 4.1.1 on 2023-08-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0009_asociarmaestro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asociarmaestro',
            old_name='Observacion',
            new_name='observacion',
        ),
    ]
