# Generated by Django 4.1.1 on 2023-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0010_rename_observacion_asociarmaestro_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociarmaestro',
            name='saldo_a_deber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asociarmaestro',
            name='saldo_inicial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
