# Generated by Django 4.1.1 on 2023-08-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0013_remove_factura_nombre_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='nombre_proyecto',
        ),
    ]
