# Generated by Django 4.1.1 on 2023-08-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0014_remove_boleta_nombre_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
