# Generated by Django 4.1.1 on 2023-09-07 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0016_factura_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapeleraReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Proyecto', 'Proyecto'), ('Maestro', 'Maestro')], max_length=10)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_que_elimino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
