# Generated by Django 4.1.1 on 2023-09-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0017_papelerareciclaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Eliminado', 'Eliminado')], default='Activo', max_length=10),
        ),
    ]
