# Generated by Django 4.1.1 on 2023-09-08 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0019_remove_papelerareciclaje_usuario_que_elimino'),
    ]

    operations = [
        migrations.AddField(
            model_name='papelerareciclaje',
            name='usuario_que_elimino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
