# Generated by Django 4.1.1 on 2023-09-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0020_papelerareciclaje_usuario_que_elimino'),
    ]

    operations = [
        migrations.AddField(
            model_name='papelerareciclaje',
            name='maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.maestro'),
        ),
    ]
