# Generated by Django 4.1.1 on 2023-09-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0023_asociarmaterial_cantidad_devuelta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociarmaterial',
            name='cantidad_devuelta',
        ),
    ]
