# Generated by Django 4.1.1 on 2023-09-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0024_remove_asociarmaterial_cantidad_devuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociarmaterial',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
