# Generated by Django 4.1.1 on 2023-09-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0025_asociarmaterial_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociarmaterial',
            name='estado',
        ),
    ]
