# Generated by Django 4.1.1 on 2023-09-13 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0026_remove_asociarmaterial_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asociada', models.PositiveIntegerField()),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.materiales')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.proyecto')),
            ],
        ),
    ]
