# Generated by Django 4.1.1 on 2023-09-13 03:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0028_historialasociacionmaestro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialAsociacion',
            new_name='HistorialAsociacionMateriales',
        ),
    ]
