# Generated by Django 4.1.1 on 2023-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0030_boleta_estado_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Eliminado', 'Eliminado')], default='Activo', max_length=10),
        ),
    ]
