# Generated by Django 4.1.1 on 2023-09-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0031_materiales_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='proyecto',
        ),
    ]
