# Generated by Django 4.1.1 on 2023-09-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0033_alter_asociarmaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociarmaterial',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Eliminado', 'Eliminado')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='asociarmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin_APP.materiales'),
        ),
    ]
