# Generated by Django 4.1.1 on 2023-09-15 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0034_asociarmaterial_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociarmaterial',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
