# Generated by Django 4.1.1 on 2023-09-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0035_alter_asociarmaterial_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociarmaterial',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
