# Generated by Django 4.1.1 on 2023-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0039_rename_userprofile_usuarioextendido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Mensual', 'Mensual'), ('3 Meses', '3 Meses'), ('Anual', 'Anual')], default='Mensual', max_length=10)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
