# Generated by Django 4.1.1 on 2023-11-06 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabin_APP', '0040_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_usuario', models.CharField(choices=[('Mensual', 'Mensual'), ('3 Meses', '3 Meses'), ('Anual', 'Anual')], default='Mensual', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioExtendido',
        ),
    ]
