# Generated by Django 4.1.1 on 2023-11-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0041_planusuario_delete_usuario_delete_usuarioextendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='planusuario',
            name='fecha_registro',
            field=models.DateTimeField(null=True),
        ),
    ]
