# Generated by Django 4.1.1 on 2023-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0046_alter_asociarboleta_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planusuario',
            name='admin_active',
            field=models.BooleanField(default=False),
        ),
    ]
