# Generated by Django 4.1.1 on 2023-11-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_APP', '0047_planusuario_admin_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planusuario',
            name='admin_active',
        ),
    ]
